# Generated by Django 4.2.25 on 2025-10-03 16:22

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, unique=True)),
                ('answer', models.TextField()),
                ('aliases', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
            ],
        ),
    ]
